### PR TITLE
several changes

### PR DESCRIPTION
**Pull request by ero-qt**
Shortened pointers, shortened logic, removed all but one of the declarations and replaced with hashset, changed deeppointer logic, removed entire update block so nothing runs every frame anymore.

I have not gotten any feedback, as it seems that nobody is willing to actually test this for me. It works for me and hope there are no errors, but it's impossible for me to test every scenario. Pointers for any version other than 12/18 are not 100% sure to work, but it's close to 90%.

### CODE REVIEW

**Comment by ero-qt** [comment]
Can't be bothered with waiting anymore.

**Comment by cursedtoast** [comment]
Good stuff, never asked for a rewrite to test/support. Thanks.

**Comment by ero-qt** [comment]
Don't make your code open source then. I just wanted to help. If your code is bad and you keep it open source, you can expect someone to come around and fix it.

**Comment by cursedtoast** [comment]
Oh, get bent. I've stated publicly I'll revisit it when time allows. 

Code is open soured for learning purposes, as stated. It's not broken code, and the way it's written doesn't cause any issues. Yes, it can be improved, which I intend to do. But you come in and get mad that I don't approve things because I can't test them personally and verify it won't break a splitter that's worked JUST FINE for nearly two years.

Your refactor accomplishes nothing but tidiness -- which is fine. But unless something is actually wrong and broken, I see no reason to prioritize it until I can personally verify.

**Pull request closed without merging**
